language: R
sudo: required
cache: packages
r:
  - release
  #- dev

warnings_are_errors: true

r_github_packages:
  - cran/survival
  - cran/bindrcpp
  - r-dbi/DBI
  - r-dbi/RPostgres
  - r-lib/covr
  - r-spatial/stars

r_binary_packages:
  - rgdal
  - sp
  - rgeos

before_install:
  # install postgis from source:
  - wget http://download.osgeo.org/postgis/source/postgis-2.3.2.tar.gz
  - (mv postgis* /tmp; cd /tmp; tar xzf postgis-2.3.2.tar.gz)
  - (cd /tmp/postgis-2.3.2 ; ./configure; make; sudo make install)

  # activate liblwgeom by:
  - sudo ldconfig
  # create postgis databases:
  - sudo service postgresql restart
  - createdb postgis
  - psql -d postgis -c "CREATE EXTENSION postgis;"
  - psql -d postgis -c "GRANT CREATE ON DATABASE postgis TO travis"
  - psql -d postgis -c "GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO travis"
  - createdb empty
  - psql -d empty -c "CREATE EXTENSION postgis;"
  - R -q -e 'install.packages("remotes"); remotes::install_github("ropenscilabs/tic"); tic::prepare_all_stages()'

after_success:
  - dropdb postgis
  - dropdb empty
  - createdb postgis
  - psql -d postgis -c "CREATE EXTENSION postgis;"
  - psql -d postgis -c "GRANT CREATE ON DATABASE postgis TO travis"
  - psql -d postgis -c "GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO travis"
  - createdb empty
  - psql -d empty -c "CREATE EXTENSION postgis;"
  - R -q -e 'covr::codecov(quiet = FALSE)'

addons:
  apt:
    packages:
      - libudunits2-dev

