language: R
sudo: required
cache: packages
r:
  - release
  #- dev

warnings_are_errors: true

r_github_packages:
  - cran/survival
  - cran/bindrcpp
  - r-dbi/DBI
  - r-dbi/RPostgres
  - r-lib/covr

r_binary_packages:
  - rgdal
  - sp
  - rgeos

addons:
  apt:
    packages:
      - libudunits2-dev

